services:
  - type: web
    name: school-management-system
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: NEXTAUTH_URL
        value: https://school-management-system.onrender.com
      - key: NEXTAUTH_SECRET
        sync: false
    healthCheckPath: /
    autoDeploy: true
